/**
 * @fileoverview Message data model for managing chat messages in conversations.
 *
 * This module implements the Message class, providing functionality for storing and
 * managing chat messages within the contractor database system.  Each message includes
 * author information, text content, timestamp, and per-user metadata such as read status,
 * archived status, starred status, and soft deletion.
 *
 * The Message model supports multi-user conversations where each user can independently
 * manage their view of messages (marking as read, archiving, starring, or soft-deleting)
 * without affecting other users' views of the same message.
 *
 * Key features:
 * - Comprehensive message information storage (author, text, timestamp, conversation ID)
 * - Per-user message state management (read, archived, starred, deleted)
 * - Automatic timestamp generation via Firebase serverTimestamp
 * - Soft deletion with timestamp tracking per user
 * - Firebase-compatible document serialization
 * - Validation for all properties and operations
 *
 * @example
 * import { doc, getDoc, setDoc, collection, addDoc, query, where, getDocs } from "firebase/firestore";
 * import { db } from "../firebase";
 * import Message from "../models/Message";
 *
 * // Fetch a document from Firebase using automatic converter
 *
 * const messageRef = doc(db, "messages", messageId).withConverter(Message.firebaseConverter);
 * const messageSnap = await getDoc(messageRef);
 * const message = messageSnap.data();  // Already a Message instance
 *
 * // Access message data
 *
 * console.log(`Author: ${message.author}`);
 * console.log(`Text: ${message.text}`);
 *
 * // Update message properties and save back to Firebase (automatic conversion to plain object)
 *
 * message.text = "This message has been edited.";
 * await setDoc(messageRef, message);
 *
 * // Or update specific fields without converter
 *
 * const newMessageData = message.toFirebaseDocument();
 * newMessageData.text = "This message has been edited without automatic conversion.";
 * await updateDoc(doc(db, "messages", messageId), newMessageData);
 *
 * @module models/Message
 * @requires firebase/firestore
 * @requires constants/data
 */

import { serverTimestamp } from "firebase/firestore";
import { isValidFirebaseUserUID, enforceTimestamp } from "../constants/data";
import { enforceTrimmedString } from "../constants/data";

/**
 * Message model for storing a single message in a conversation.
 *
 * This class encapsulates message information including author, text content, timestamp,
 * and per-user metadata.  It provides methods for managing message state independently
 * for each user (read, archived, starred, deleted status).
 *
 * Messages support soft deletion, where each user can delete a message from their view
 * without affecting other users.  The deletion is tracked with a timestamp per user.
 *
 * @class Message
 * @example
 * const message = new Message({
 *   conversationId: "conv_0123",
 *   author: "user_0456",
 *   text: "Hello, how are you?"
 * });
 */
class Message {
  // Static private members

  /**
   * Current authenticated user's ID (set once during app initialization)
   * @private
   * @static
   * @type {?string}
   */
  static #currentUserId = null;

  // Static getters

  /**
   * Get the current user's ID.
   * @static
   * @returns {?string} Current user ID, or null if not set
   */
  static get currentUserId() {
    return Message.#currentUserId;
  }

  // Static setters

  /**
   * Set the current user ID context for all Message instances.
   *
   * This should be set whenever a user logs in or logs out.
   *
   * @static
   * @param {?string} userId - The authenticated user's ID, or null to clear
   * @throws {Error} If userId is not valid
   * @example
   * import { UserAuth } from '../contexts/Authorization';
   * import Message from '../models/Message';
   *
   * function App() {
   *   const { userId } = UserAuth();
   *
   *   useEffect(() => {
   *     Message.currentUserId = userId;
   *   }, [userId]);
   * }
   */
  static set currentUserId(userId) {
    if ((userId !== null) && !isValidFirebaseUserUID(userId)) {
      throw new Error("userId must be either null or a valid Firebase UserUID");
    }

    Message.#currentUserId = userId;
  }

  // Private members

  /**
   * Array of user IDs who have archived this message
   * @private
   * @type {string[]}
   */
  #archivedBy = [];

  /**
   * User ID of the message author
   * @private
   * @type {string}
   */
  #author;  // See constructor for default initial value

  /**
   * ID of the conversation this message belongs to
   * @private
   * @type {string}
   */
  #conversationId = "";

  /**
   * Timestamp when the message was created (generated by Firebase serverTimestamp())
   * @private
   * @type {?Timestamp}
   */
  #createdOn = null;

  /**
   * Array of deletion records, each containing userId and timestamp
   * @private
   * @type {Array<{userId: string, timestamp: Timestamp}>}
   */
  #deletedOnBy = [];

  /**
   * Array of user IDs who have read this message
   * @private
   * @type {string[]}
   */
  #readBy = [];

  /**
   * Array of user IDs who have starred this message
   * @private
   * @type {string[]}
   */
  #starredBy = [];

  /**
   * The message text content
   * @private
   * @type {string}
   */
  #text = "";

  // Constructor

  /**
   * Create a new Message instance.
   *
   * When creating a brand new message (as opposed to populating a new instance with existing
   * data), set the "createdOn" member to "null" -- the timestamp will be generated
   * automatically by Firebase when the instance is first saved.  If no author is provided then
   * the current user ID will be used as the author.
   *
   * @constructor
   * @param {Object} [data={}] - Message data object
   * @param {string[]} [data.archivedBy=[]] - Array of user IDs who have archived this message
   * @param {string} [data.author=""] - User ID of the message author (defaults to current user)
   * @param {string} [data.conversationId=""] - ID of the conversation this message belongs to
   * @param {Timestamp} [data.createdOn] - Message creation timestamp (auto-generated by Firebase)
   * @param {Array<{userId: string, timestamp: Timestamp}>} [data.deletedOnBy=[]] - Array of deletion records
   * @param {string[]} [data.readBy=[]] - Array of user IDs who have read this message
   * @param {string[]} [data.starredBy=[]] - Array of user IDs who have starred this message
   * @param {string} [data.text=""] - The message text content
   */
  constructor(data = {}) {
    /*
    This constructor considers the possibility that data may be invalid or missing and will add
    default values to its members where necessary to maintain data integrity.
    */

    if (typeof data === "object" && !Array.isArray(data)) {
      this.#author = (isValidFirebaseUserUID(data.author) ? data.author : (Message.#currentUserId || ""));
      this.#conversationId = (typeof data.conversationId === "string" ? data.conversationId : this.#conversationId);
      this.#createdOn = enforceTimestamp(data.createdOn);
      this.#text = enforceTrimmedString(data.text);

      // Process archivedBy array

      if (Array.isArray(data.archivedBy)) {
        data.archivedBy.forEach((userId) => {
          if (isValidFirebaseUserUID(userId)) {
            this.#archivedBy.push(userId);
          }
        });
      }

      // Process deletedOnBy array

      if (Array.isArray(data.deletedOnBy)) {
        data.deletedOnBy.forEach((deletionData) => {
          const timestamp = enforceTimestamp(deletionData.timestamp);

          if (isValidFirebaseUserUID(deletionData.userId) && timestamp) {
            this.#deletedOnBy.push({ userId: deletionData.userId, timestamp });
          }
        });
      }

      // Process readBy array

      if (Array.isArray(data.readBy)) {
        data.readBy.forEach((userId) => {
          if (isValidFirebaseUserUID(userId)) {
            this.#readBy.push(userId);
          }
        });
      }

      // Process starredBy array

      if (Array.isArray(data.starredBy)) {
        data.starredBy.forEach((userId) => {
          if (isValidFirebaseUserUID(userId)) {
            this.#starredBy.push(userId);
          }
        });
      }
    }
    else {
      this.#author = (Message.#currentUserId || "");
    }
  }

  // Getters

  /**
   * Get the author's user ID.
   * @returns {string} Author user ID
   */
  get author() { return this.#author; }

  /**
   * Get the conversation ID this message belongs to.
   * @returns {string} Conversation ID
   */
  get conversationId() { return this.#conversationId; }

  /**
   * Get the message creation timestamp.
   * @returns {?Timestamp} Message timestamp, or null if not yet saved to Firebase
   */
  get createdOn() { return this.#createdOn; }

  /**
   * Get the message text content.
   * @returns {string} Message text
   */
  get text() { return this.#text; }

  /**
   * Check if this message is archived by the current user.
   * @returns {boolean} True if archived by current user
   * @throws {Error} If current user is not set
   */
  get isArchived() {
    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    return this.#archivedBy.includes(userId);
  }

  /**
   * Check if this message was deleted by the current user.
   * @returns {boolean} True if deleted by current user
   * @throws {Error} If current user is not set
   */
  get isDeleted() {
    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    return this.#deletedOnBy.some((deletionData) => deletionData.userId === userId);
  }

  /**
   * Check if this message has been read by the current user.
   * @returns {boolean} True if read by current user
   * @throws {Error} If current user is not set
   */
  get isRead() {
    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    return this.#readBy.includes(userId);
  }

  /**
   * Check if this message is starred by the current user.
   * @returns {boolean} True if starred by current user
   * @throws {Error} If current user is not set
   */
  get isStarred() {
    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    return this.#starredBy.includes(userId);
  }

  // Setters with validation

  /**
   * Set the message text content.
   * @param {string} value - The new message text (must be non-empty after trimming)
   * @throws {Error} If value is not a non-empty string
   */
  set text(value) {
    const newValue = enforceTrimmedString(value);

    if (newValue === "") {
      throw new Error("Value must be a non-empty string");
    }

    this.#text = newValue;
  }

  /**
   * Archive or unarchive this message for the current user.
   * @param {boolean} value - True to archive, false to unarchive
   * @throws {Error} If current user is not set or value is not a boolean
   */
  set isArchived(value) {
    if (typeof value !== "boolean") {
      throw new Error("Value must be a boolean");
    }

    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    const messageIsArchived = this.#archivedBy.includes(userId);

    if (value && !messageIsArchived) {
      this.#archivedBy.push(userId);
    } else if (!value && messageIsArchived) {
      this.#archivedBy = this.#archivedBy.filter((id) => id !== userId);
    }
  }

  /**
   * Delete or undelete this message for the current user.
   * @param {boolean} value - True to delete, false to undelete
   * @throws {Error} If current user is not set or deleted is not a boolean
   */
  set isDeleted(value) {
    if (typeof value !== "boolean") {
      throw new Error("Value must be a boolean");
    }

    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    const messageIsDeleted = this.#deletedOnBy.some((deletionData) => deletionData?.userId === userId);

    if (value && !messageIsDeleted) {
      this.#deletedOnBy.push({ userId, timestamp:  serverTimestamp() });
    } else if (!value && messageIsDeleted) {
      this.#deletedOnBy = this.#deletedOnBy.filter((deletionData) => deletionData?.userId !== userId);
    }
  }

  /**
   * Mark this message as read or unread by the current user.
   * @param {boolean} value - True to mark as read, false to mark as unread
   * @throws {Error} If current user is not set or value is not a boolean
   */
  set isRead(value) {
    if (typeof value !== "boolean") {
      throw new Error("Value must be a boolean");
    }

    const userId = Message.#currentUserId;

    if (userId === null) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    const messageIsRead = this.#readBy.includes(userId);

    if (value && !messageIsRead) {
      this.#readBy.push(userId);
    } else if (!value && messageIsRead) {
      this.#readBy = this.#readBy.filter((id) => id !== userId);
    }
  }

  /**
   * Star or unstar this message for the current user.
   * @param {boolean} value - True to star, false to unstar
   * @throws {Error} If current user is not set or value is not a boolean
   */
  set isStarred(value) {
    if (typeof value !== "boolean") {
      throw new Error("Value must be a boolean");
    }

    const userId = Message.#currentUserId;

    if (!userId) {
      throw new Error("Current user not set.  Call Message.setCurrentUser() first.");
    }

    const messageIsStarred = this.#starredBy.includes(userId);

    if (value && !messageIsStarred) {
      this.#starredBy.push(userId);
    } else if (!value && messageIsStarred) {
      this.#starredBy = this.#starredBy.filter((id) => id !== userId);
    }
  }

  // Methods

  /**
   * Convert the Message instance to a plain object suitable for storing in Firebase.
   *
   * This method serializes all message data into a format that can be directly written to
   * Firebase or embedded in other documents.
   *
   * @returns {Object} Plain object representation of the message data
   */
  toFirebaseDocument() {
    const doc = {
      archivedBy:  this.#archivedBy,
      author:  this.#author,
      conversationId:  this.#conversationId,
      deletedOnBy:  this.#deletedOnBy,
      readBy:  this.#readBy,
      starredBy:  this.#starredBy,
      text:  this.#text
    };

    // Only set createdOn if we're creating a new document

    if (!this.#createdOn) {
      doc.createdOn = serverTimestamp();
    }

    return doc;
  }

  /**
   * Firestore converter for automatic serialization and deserialization of Message instances.
   *
   * Use this converter with Firestore document references to automatically convert between
   * Message instances and Firestore documents.  This is the recommended approach for Firestore
   * operations.
   *
   * @static
   * @type {Object}
   * @property {Function} fromFirestore - Converts Firestore document to Message instance
   * @property {Function} toFirestore - Converts Message instance to Firestore document
   * @example
   * const projectRef = doc(db, "messages", messageId).withConverter(Message.firebaseConverter);
   *
   * // Reading returns a Message instance
   *
   * const messageSnap = await getDoc(messageRef);
   * const message = messageSnap.data();  // Returns Message instance
   *
   * // Writing accepts a Message instance
   *
   * const newMessage = new Message({
   *   text:  "This message is in a bottle."
   * });
   * await setDoc(messageRef, newMessage);
   */
  static firebaseConverter = {
    fromFirestore:  (snapshot, options) => new Message(snapshot.data(options)),
    toFirestore:  (message) => message.toFirebaseDocument()
  };
}

export default Message;