/**
 * @fileoverview UserViewed data model for tracking profile view events.
 *
 * This model records when one user views another user's profile, storing the viewer, the
 * viewed user, and the timestamp of the view.  This data can be used for analytics,
 * notifications, or displaying "who viewed your profile" features.
 *
 * Key features:
 * - Automatic timestamp generation for new view records
 * - Validation of user IDs
 * - Firebase Firestore integration with converter
 * - Immutable data structure (no setters)
 *
 * @example
 * // Create a new profile view record
 *
 * const viewRecord = new UserViewed({
 *   viewingUser: "user_0123",
 *   viewedUser: "user_0456"
 * });
 *
 * // Save to Firestore
 *
 * const viewRef = doc(db, "userViews", viewId).withConverter(UserViewed.firebaseConverter);
 * await setDoc(viewRef, viewRecord);
 *
 * // Query views of a specific user
 *
 * const viewsQuery = query(
 *   collection(db, "userViews").withConverter(UserViewed.firebaseConverter),
 *   where("viewedUser", "==", userId),
 *   orderBy("timestamp", "desc")
 * );
 * const viewsSnapshot = await getDocs(viewsQuery);
 * const views = viewsSnapshot.docs.map(doc => doc.data());  // Already UserViewed instances
 *
 * @module models/UserViewed
 * @requires firebase/firestore
 * @requires constants/data
 */

import { serverTimestamp } from "firebase/firestore";
import { isValidFirebaseUserUID, enforceTimestamp } from "../constants/data";

/**
 * UserViewed model for tracking profile view events.
 *
 * Records when one user views another user's profile, including the timestamp
 * of the view.  This is a simple, immutable record.
 *
 * Note: This class has no setters - view records are immutable once created.
 *
 * @class UserViewed
 */
class UserViewed {
  // Private members

  /**
   * Timestamp when the profile view occurred (null until saved to Firebase)
   *
   * @private
   * @type {?Timestamp}
   */
  #timestamp = null;

  /**
   * User ID of the user whose profile was viewed
   *
   * @private
   * @type {string}
   */
  #viewedUser = "";

  /**
   * User ID of the user who viewed the profile
   *
   * @private
   * @type {string}
   */
  #viewingUser = "";

  // Constructor

  /**
   * Create a new UserViewed instance.
   *
   * When creating a brand new view record (as opposed to populating a new instance with
   * existing data), set the "timestamp" member to null – the timestamp will be generated
   * automatically by Firebase when the instance is first saved.
   *
   * @constructor
   * @param {Object} [data={}] - User view data object
   * @param {Timestamp} [data.timestamp] - View timestamp (auto-generated by Firebase for new records)
   * @param {string} [data.viewedUser=""] - User ID of the viewed user
   * @param {string} [data.viewingUser=""] - User ID of the viewing user
   */
  constructor(data = {}) {
    /*
    This constructor considers the possibility that data may be invalid or missing and will add
    default values to its members where necessary to maintain data integrity.
    */

    if (data && typeof data === "object" && !Array.isArray(data)) {
      // Initialize from data or use defaults
      this.#timestamp = (data.timestamp ? enforceTimestamp(data.timestamp) : this.#timestamp);
      this.#viewedUser = isValidFirebaseUserUID(data.viewedUser) ? data.viewedUser : this.#viewedUser;
      this.#viewingUser = isValidFirebaseUserUID(data.viewingUser) ? data.viewingUser : this.#viewingUser;
    }
  }

  // Getters

  /**
   * Get the timestamp when the profile view occurred.
   *
   * @returns {?Timestamp} View timestamp, or null if not yet saved to Firebase
   */
  get timestamp() { return this.#timestamp; }

  /**
   * Get the user ID of the user whose profile was viewed.
   *
   * @returns {string} Viewed user's ID
   */
  get viewedUser() { return this.#viewedUser; }

  /**
   * Get the user ID of the user who viewed the profile.
   *
   * @returns {string} Viewing user's ID
   */
  get viewingUser() { return this.#viewingUser; }

  // Methods

  /**
   * Convert this user view record to a plain JavaScript object suitable for Firebase Firestore.
   *
   * This method prepares the view data for storage in Firestore.  The timestamp is only
   * included if it's not already set (i.e., when creating a new document), in which case
   * it will be set to serverTimestamp() to ensure accurate server-side timing.
   *
   * @returns {Object} Plain object representation of the user view for Firestore
   */
  toFirebaseDocument() {
    const doc = {
      viewedUser:  this.#viewedUser,
      viewingUser:  this.#viewingUser
    };

    // Only set timestamp if we're creating a new document

    if (!this.#timestamp) {
      doc.timestamp = serverTimestamp();
    }

    return doc;
  }

  /**
   * Firebase Firestore converter for automatic conversion between UserViewed instances and
   * Firestore documents.
   *
   * This converter enables direct use of UserViewed instances with Firestore operations:
   * - `doc.withConverter(UserViewed.firebaseConverter)` for reading/writing documents
   * - Automatic conversion from Firestore document to UserViewed instances
   * - Automatic conversion from UserViewed instances to Firestore documents
   *
   * @static
   * @type {Object}
   * @property {Function} fromFirestore - Converts Firestore document to UserViewed instance
   * @property {Function} toFirestore - Converts UserViewed instance to Firestore document
   * @example
   * // Reading a view record from Firestore
   *
   * const viewRef = doc(db, "userViews", viewId).withConverter(UserViewed.firebaseConverter);
   * const viewSnap = await getDoc(viewRef);
   * const viewRecord = viewSnap.data();  // Already a UserViewed instance
   *
   * // Writing a view record to Firestore
   *
   * await setDoc(viewRef, viewRecord);  // Automatically converted to plain object
   */
  static firebaseConverter = {
    fromFirestore:  (snapshot, options) => new UserViewed(snapshot.data(options)),
    toFirestore:  (userViewed) => userViewed.toFirebaseDocument()
  };
}

export default UserViewed;